# Generated by Django 5.1.2 on 2024-10-25 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_Estimada', models.FloatField()),
                ('fecha_Inicio', models.DateField()),
                ('fecha_Finalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('correoElectronico', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.TextField()),
                ('fecha_Registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Progreso', 'En progreso'), ('Completada', 'Completada')], max_length=50)),
                ('completada', models.BooleanField()),
                ('fecha_Creacion', models.DateField()),
                ('hora_Vencimiento', models.TimeField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.etiqueta')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='tarea',
            field=models.ManyToManyField(through='Gestion_Tarea.Tarea_Etiqueta', to='Gestion_Tarea.tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ManyToManyField(through='Gestion_Tarea.Asignacion_Tarea', to='Gestion_Tarea.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_Comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tarea.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ManyToManyField(through='Gestion_Tarea.Usuario_Proyecto', to='Gestion_Tarea.usuario'),
        ),
    ]
